(function() {function f(a){throw a;}var h=void 0,j=!0,l=null,n=!1;function q(a){return function(){return this[a]}}function v(a){return function(){return a}}var w,x=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return a!==h}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){return"string"==typeof a}function ca(a){return"number"==typeof a}Math.floor(2147483648*Math.random()).toString(36);function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return A.apply(l,arguments)}function fa(a,b){function c(){}c.prototype=b.prototype;a.sc=b.prototype;a.prototype=new c};function C(a,b,c){this.type=a;this.T=b;this.La=c};function ga(a){a=""+a;if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function ha(){this.bb=h}
function ia(a,b,c){switch(typeof b){case "string":ja(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if("array"==aa(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ia(a,a.bb?a.bb.call(b,""+g,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),ja(g,
c),c.push(":"),ia(a,a.bb?a.bb.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var ka={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},la=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ja(a,b){b.push('"',a.replace(la,function(a){if(a in ka)return ka[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ka[a]=e+b.toString(16)}),'"')};function ma(a){if("undefined"!==typeof JSON&&y(JSON.stringify))a=JSON.stringify(a);else{var b=[];ia(new ha,a,b);a=b.join("")}return a};function D(a,b){this.qa=a?a:na;this.J=b?b:oa}function na(a,b){return a<b?-1:a>b?1:0}w=D.prototype;w.P=function(a,b){return new D(this.qa,this.J.P(a,b,this.qa).copy(l,l,n,l,l))};w.remove=function(a){return new D(this.qa,this.J.remove(a,this.qa).copy(l,l,n,l,l))};w.get=function(a){for(var b,c=this.J;!c.a();){b=this.qa(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return l};
function pa(a,b){for(var c,d=a.J,e=l;!d.a();){c=a.qa(b,d.key);if(0===c){if(d.left.a())return e?e.key:l;for(d=d.left;!d.right.a();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}f("Attempted to find predecessor key for a nonexistent key.  What gives?")}w.a=function(){return this.J.a()};w.count=function(){return this.J.count()};w.Fa=function(){return this.J.Fa()};w.ua=function(){return this.J.ua()};w.X=function(a){return this.J.X(a)};w.ha=function(a){return this.J.ha(a)};
w.sa=function(a){return new qa(this.J,a)};function qa(a,b){this.Ib=b;for(this.Ua=[];!a.a();)this.Ua.push(a),a=a.left}function sa(a){if(0===a.Ua.length)return l;var b=a.Ua.pop(),c;c=a.Ib?a.Ib(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.a();)a.Ua.push(b),b=b.left;return c}function ta(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=l?c:j;this.left=d!=l?d:oa;this.right=e!=l?e:oa}w=ta.prototype;
w.copy=function(a,b,c,d,e){return new ta(a!=l?a:this.key,b!=l?b:this.value,c!=l?c:this.color,d!=l?d:this.left,e!=l?e:this.right)};w.count=function(){return this.left.count()+1+this.right.count()};w.a=v(n);w.X=function(a){return this.left.X(a)||a(this.key,this.value)||this.right.X(a)};w.ha=function(a){return this.right.ha(a)||a(this.key,this.value)||this.left.ha(a)};function ua(a){return a.left.a()?a:ua(a.left)}w.Fa=function(){return ua(this).key};w.ua=function(){return this.right.a()?this.key:this.right.ua()};
w.P=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(l,l,l,e.left.P(a,b,c),l):0===d?e.copy(l,b,l,l,l):e.copy(l,l,l,l,e.right.P(a,b,c));return va(e)};function wa(a){if(a.left.a())return oa;!a.left.n()&&!a.left.left.n()&&(a=xa(a));a=a.copy(l,l,l,wa(a.left),l);return va(a)}
w.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.a()&&!c.left.n()&&!c.left.left.n()&&(c=xa(c)),c=c.copy(l,l,l,c.left.remove(a,b),l);else{c.left.n()&&(c=ya(c));!c.right.a()&&!c.right.n()&&!c.right.left.n()&&(c=za(c),c.left.left.n()&&(c=ya(c),c=za(c)));if(0===b(a,c.key)){if(c.right.a())return oa;d=ua(c.right);c=c.copy(d.key,d.value,l,l,wa(c.right))}c=c.copy(l,l,l,l,c.right.remove(a,b))}return va(c)};w.n=q("color");
function va(a){a.right.n()&&!a.left.n()&&(a=Aa(a));a.left.n()&&a.left.left.n()&&(a=ya(a));a.left.n()&&a.right.n()&&(a=za(a));return a}function xa(a){a=za(a);a.right.left.n()&&(a=a.copy(l,l,l,l,ya(a.right)),a=Aa(a),a=za(a));return a}function Aa(a){return a.right.copy(l,l,a.color,a.copy(l,l,j,l,a.right.left),l)}function ya(a){return a.left.copy(l,l,a.color,l,a.copy(l,l,j,a.left.right,l))}
function za(a){var b,c;b=a.left.copy(l,l,!a.left.color,l,l);c=a.right.copy(l,l,!a.right.color,l,l);return a.copy(l,l,!a.color,b,c)}function Ba(){}w=Ba.prototype;w.copy=function(){return this};w.P=function(a,b){return new ta(a,b,h,h,h)};w.remove=function(){return this};w.get=v(l);w.count=v(0);w.a=v(j);w.X=v(n);w.ha=v(n);w.Fa=v(l);w.ua=v(l);w.n=v(n);var oa=new Ba;var Ca=/^[a-zA-Z0-9\-_.!~*'()]*$/;function Da(a){a=""+a;return!Ca.test(a)?encodeURIComponent(a):a};function E(a){if(a instanceof E)return a;if(1==arguments.length){this.g=a.split("/");for(var b=0,c=0;c<this.g.length;c++)0<this.g[c].length&&(this.g[b]=this.g[c],b++);this.g.length=b;this.I=0}else this.g=arguments[0],this.I=arguments[1]}function H(a){return a.I>=a.g.length?l:a.g[a.I]}function I(a){var b=a.I;b<a.g.length&&b++;return new E(a.g,b)}function Ea(a){return a.I<a.g.length?a.g[a.g.length-1]:l}
E.prototype.toString=function(){for(var a="",b=this.I;b<this.g.length;b++)""!==this.g[b]&&(a+="/"+this.g[b]);return a};E.prototype.parent=function(){if(this.I>=this.g.length)return l;for(var a=[],b=this.I;b<this.g.length-1;b++)a.push(this.g[b]);return new E(a,0)};E.prototype.k=function(a){for(var b=[],c=this.I;c<this.g.length;c++)b.push(this.g[c]);if(a instanceof E)for(c=a.I;c<a.g.length;c++)b.push(a.g[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new E(b,0)};
E.prototype.a=function(){return this.I>=this.g.length};function Fa(a,b){var c=H(a);if(c===l)return b;if(c===H(b))return Fa(I(a),I(b));f("INTERNAL ERROR: innerParsedPath ("+b+") is not within outerParsedPath ("+a+")")};function Ga(a,b){this.oa=a;this.ya="undefined"!==typeof b?b:l}w=Ga.prototype;w.Q=v(j);w.f=q("ya");w.ib=function(a){return new Ga(this.oa,a)};w.t=function(){return J};w.e=function(a){return H(a)===l?this:J};w.G=v(l);w.q=function(a,b){return(new K(new D,this.ya)).q(a,b)};w.Aa=function(a,b){var c=H(a);return c===l?b:this.q(c,J.Aa(I(a),b))};w.a=v(n);w.z=function(a){return a&&this.f()!==l?{".value":this.c(),".priority":""+this.f()}:this.c()};
w.hash=function(){var a="";this.f()!==l&&(a+="priority:"+this.f()+":");a+=typeof this.oa+":"+this.oa;return Ha(a)};w.c=q("oa");w.toString=function(){return"string"===typeof this.oa?'"'+this.oa+'"':this.oa};function K(a,b){this.D=a||new D;this.ya="undefined"!==typeof b?b:l}w=K.prototype;w.Q=v(n);w.f=q("ya");w.ib=function(a){return new K(this.D,a)};w.q=function(a,b){var c=this.D.remove(a);b&&b.a()&&(b=l);b!==l&&(c=c.P(a,b));return b&&b.f()!==l?new Ia(c,l,this.ya):new K(c,this.ya)};
w.Aa=function(a,b){var c=H(a);if(c===l)return b;var d=this.t(c).Aa(I(a),b);return this.q(c,d)};w.a=function(){return this.D.a()};var Ja=/^\d+$/;w=K.prototype;w.z=function(a){if(this.a())return l;var b={},c=0,d=0,e=j;this.p(function(g,i){b[g]=i.z(a);c++;e&&Ja.test(g)?d=Math.max(d,Number(g)):e=n});if(!a&&e&&d<2*c){var g=[],i;for(i in b)g[i]=b[i];return g}a&&this.f()!==l&&(b[".priority"]=""+this.f());return b};
w.hash=function(){var a="";this.f()!==l&&(a+="priority:"+this.f()+":");this.p(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Ha(a)};w.t=function(a){a=this.D.get(a);return a===l?J:a};w.e=function(a){var b=H(a);return b===l?this:this.t(b).e(I(a))};w.G=function(a){return pa(this.D,a)};w.Ab=function(){return this.D.Fa()};w.Cb=function(){return this.D.ua()};w.p=function(a){return this.D.X(a)};w.mb=function(a){return this.D.ha(a)};w.sa=function(){return this.D.sa()};
w.toString=function(){var a="{",b=j;this.p(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var J=new K(new D);function Ia(a,b,c){K.call(this,a,c);b===l&&(b=new D(Ka),a.X(function(a,c){b=b.P({name:a,ga:c.f()},c)}));this.ka=b}fa(Ia,K);w=Ia.prototype;w.q=function(a,b){var c=this.t(a),d=this.D,e=this.ka;c!==l&&(d=d.remove(a),e=e.remove({name:a,ga:c.f()}));b&&b.a()&&(b=l);b!==l&&(d=d.P(a,b),e=e.P({name:a,ga:b.f()},b));return new Ia(d,e,this.f())};
w.G=function(a,b){var c=pa(this.ka,{name:a,ga:b.f()});return c?c.name:l};w.p=function(a){return this.ka.X(function(b,c){return a(b.name,c)})};w.mb=function(a){return this.ka.ha(function(b,c){return a(b.name,c)})};w.sa=function(){return this.ka.sa(function(a,b){return{key:a.name,value:b}})};w.Ab=function(){return this.ka.Fa().name};w.Cb=function(){return this.ka.ua().name};
function La(a,b){if("object"!==typeof a)return new Ga(a,b);if(a===l)return J;var c=".priority"in a?a[".priority"]:b||l;c!==l&&(c=Ma.test(c)?Number(c):c);if(".value"in a&&a[".value"]!==l)return new Ga(a[".value"],c);var c=new K(new D,c),d;for(d in a)if("."!==d.substring(0,1)){var e=La(a[d]);if(e.Q()||!e.a())c=c.q(d,e)}return c}function Ka(a,b){return Na(a.ga,b.ga)||(a.name!==b.name?a.name<b.name?-1:1:0)};function Oa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};var Pa=/[\[\].#$\/]/,Qa=/[\[\].#$]/;function Ra(a){return z(a)&&0!==a.length&&!Pa.test(a)}function L(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&f(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function Sa(a,b,c){(!c||y(b))&&Ta(M(a,1,c),b)}
function Ta(a,b){y(b)||f(Error(a+"contains undefined."));"function"==aa(b)&&f(Error(a+"contains a function."));z(b)&&b.length>10485760/3&&10485760<Oa(b).length&&f(Error(a+"contains a string greater than 10485760 utf8 bytes ('"+b.substring(0,50)+"...')"));var c=aa(b);if("object"==c||"array"==c||"function"==c)for(var d in b)".priority"!==d&&".value"!==d&&!Ra(d)&&f(Error(a+"contains an invalid key ("+d+').  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),Ta(a,b[d])}
function Ua(a,b,c,d){(!d||y(c))&&c!==l&&!ca(c)&&!z(c)&&f(Error(M(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function N(a,b,c,d){(!d||y(c))&&"function"!=aa(c)&&f(Error(M(a,b,d)+"must be a valid function."))}function Va(a,b){switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:f(Error(M(a,1,n)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function Wa(a,b){y(b)&&!Ra(b)&&f(Error(M(a,2,j)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function Xa(a,b){(!z(b)||0===b.length||Qa.test(b))&&f(Error(M(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}
function M(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:O(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}a+=" failed: ";c&&(a+="If provided, ");return a+(d+" argument ")};function P(a,b){this.b=a;this.ab=b}P.prototype.z=function(){L("Firebase.DataSnapshot.val",0,0,arguments.length);return this.b.z()};P.prototype.val=P.prototype.z;P.prototype.Qb=function(){L("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.b.z(j)};P.prototype.exportVal=P.prototype.Qb;P.prototype.k=function(a){L("Firebase.DataSnapshot.child",0,1,arguments.length);ca(a)&&(a=""+a);Xa("Firebase.DataSnapshot.child",a);var b=new E(a),c=this.ab.k(b);return new P(this.b.e(b),c)};
P.prototype.child=P.prototype.k;P.prototype.Rb=function(a){L("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Xa("Firebase.DataSnapshot.hasChild",a);return!this.b.e(new E(a)).a()};P.prototype.hasChild=P.prototype.Rb;P.prototype.f=function(){L("Firebase.DataSnapshot.getPriority",0,0,arguments.length);var a=this.b.f();return a===l?a:""+a};P.prototype.getPriority=P.prototype.f;
P.prototype.forEach=function(a){L("Firebase.DataSnapshot.forEach",1,1,arguments.length);N("Firebase.DataSnapshot.forEach",1,a,n);if(this.b.Q())return n;var b=this;return this.b.p(function(c,d){return a(new P(d,b.ab.k(c)))})};P.prototype.forEach=P.prototype.forEach;P.prototype.Ra=function(){L("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.b.Q()?n:!this.b.a()};P.prototype.hasChildren=P.prototype.Ra;
P.prototype.name=function(){L("Firebase.DataSnapshot.name",0,0,arguments.length);return this.ab.name()};P.prototype.name=P.prototype.name;P.prototype.jc=function(){L("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.ab};P.prototype.ref=P.prototype.jc;function Ya(a){for(var b in a)return n;return j};function Za(){this.children={};this.Oa=0;this.value=l}function Q(a,b,c){this.Ta=a?a:"";this.Ja=b?b:l;this.b=c?c:new Za}function R(a,b){for(var c=b instanceof E?b:new E(b),d=a,e;(e=H(c))!==l;)d=new Q(e,d,e in d.b.children?d.b.children[e]:new Za),c=I(c);return d}w=Q.prototype;w.c=function(){return this.b.value};function S(a,b){a.b.value=b;$a(a)}w.clear=function(){this.b.value=l;this.b.children={};this.b.Oa=0;$a(this)};w.Ra=function(){return 0<this.b.Oa};w.a=function(){return this.c()===l&&!this.Ra()};
w.p=function(a){for(var b in this.b.children)a(new Q(b,this,this.b.children[b]))};function ab(a,b){a.p(function(c){b(new Q(c.name(),a,a.b.children[c.name()]));ab(c,b)})}function bb(a,b,c){for(a=c?a:a.parent();a!==l;)b(a),a=a.parent()}function cb(a,b){a.p(function(a){a.c()!==l?b(a):cb(a,b)})}function T(a,b){for(var c=a.b;c;){if(c.value!==l)return j;c=c.children[H(b)];b=I(b)}}w.path=function(){return new E(this.Ja===l?this.Ta:this.Ja.path()+"/"+this.Ta)};w.name=q("Ta");w.parent=q("Ja");
function $a(a){if(a.Ja!==l){var b=a.Ja,c=a.Ta,d=a.a(),e=c in b.b.children;d&&e?(delete b.b.children[c],b.b.Oa--,$a(b)):!d&&!e&&(b.b.children[c]=a.b,b.b.Oa++,$a(b))}};function db(){this.set={}}w=db.prototype;w.add=function(a,b){this.set[a]=b!==l?b:j};w.get=function(a){return this.set[a]};w.remove=function(a){delete this.set[a]};w.clear=function(){this.set={}};w.a=function(){for(var a in this.set)return n;return j};w.count=function(){var a=0,b;for(b in this.set)a++;return a};var eb="pLPCommand",fb="pRTLPCB";
function gb(a,b,c,d,e){this.Ga=(a.cb?"https://":"http://")+a.host+"/"+a.wa+".lp";this.xb=0;this.w=d;this.Yb=new hb(b);var g=this;this.ca=setTimeout(function(){U("Timed out trying to connect.");g.close();g.ca=l},3E4);ib(function(){if(!g.Sa){g.ia=new jb(function(a,b,d){if(g.ia)if(g.ca&&(clearTimeout(g.ca),g.ca=l),"start"==a){c();a=g.ia;a.Wb=b;a.Xb=d;for(a.jb=j;kb(a););g.va=document.createElement("iframe");g.va.src=g.Ga+"?disconn=t&id="+b+"&pw="+d;g.va.style.display="none";document.body.appendChild(g.va)}else"reset"==
a?(U("Got Server RESET packet."),g.close()):"shutdown"==a&&(U("Shutdown message received from server, likely due to unmatching version numbers."),e())},function(a,b){var c=g.Yb;for(c.Ya[a]=b;c.Ya[c.Pa];){var d=c.Ya[c.Pa];delete c.Ya[c.Pa];for(var e=0;e<d.length;e++)d[e]&&c.Vb(d[e]);c.Pa++}},function(){g.close()},g.Ga);var a=g.Ga+"?start=t&ser="+Math.floor(1E8*Math.random())+"&v=1";U("Connecting via long-poll to "+a);lb(g.ia,a,function(){})}})}
gb.prototype.close=function(){if(!this.Sa&&(this.Sa=j,U("Closing long-poll connection."),this.ia&&(this.ia.close(),this.ia=l),this.va&&(document.body.removeChild(this.va),this.va=l),this.w&&(this.w(),this.w=l),this.ca))clearTimeout(this.ca),this.ca=l};gb.prototype.send=function(a){for(var a=ma(a),a=mb(Oa(a),j),a=nb(a,1840),b=0;b<a.length;b++){var c=this.ia;c.Ka.push({nc:this.xb,qc:a.length,yb:a[b]});c.jb&&kb(c);this.xb++}};function hb(a){this.Vb=a;this.Ya=[];this.Pa=0}
function jb(a,b,c,d){this.Ga=d;this.w=c;this.sb=new db;this.Ka=[];this.lb=Math.floor(1E8*Math.random());c=qb();window[eb+c]=a;window[fb+c]=b;a=document.createElement("iframe");a.style.display="none";document.body?document.body.appendChild(a):f("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");a.contentDocument?a.W=a.contentDocument:a.contentWindow?a.W=a.contentWindow.document:a.document&&(a.W=a.document);this.R=a;a="<html><body><script>\nfunction "+
eb+'(c, a1, a2, a3, a4) {\nparent.window["'+eb+c+'"](c, a1, a2, a3, a4);\n}\nfunction '+fb+'(pN, data) {\nparent.window["'+fb+c+'"](pN, data);\n}\n<\/script></body></html>\n';this.R.W.open();this.R.W.write(a);this.R.W.close()}jb.prototype.close=function(){this.jb=n;this.R&&(this.R.W.body.innerHTML="",document.body.removeChild(this.R),this.R=l);var a=this.w;a&&(this.w=l,a())};
function kb(a){if(a.jb&&a.sb.count()<(0<a.Ka.length?2:1)){a.lb++;for(var b=a.Ga+"?id="+a.Wb+"&pw="+a.Xb+"&ser="+a.lb,c="",d=0;0<a.Ka.length;)if(1870>=a.Ka[0].yb.length+30+c.length){var e=a.Ka.shift(),c=c+"&seg"+d+"="+e.nc+"&ts"+d+"="+e.qc+"&d"+d+"="+e.yb;d++}else break;rb(a,b+c,a.lb);return j}return n}function rb(a,b,c){function d(){a.sb.remove(c);kb(a)}a.sb.add(c);var e=setTimeout(d,25E3);lb(a,b,function(){clearTimeout(e);d()})}
function lb(a,b,c){setTimeout(function(){try{var d=a.R.W.createElement("script");d.type="text/javascript";d.async=j;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=l,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){U("Long-poll script failed to load.");a.close()};a.R.W.body.appendChild(d)}catch(e){}},1)}
function nb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c};var sb=l;"undefined"!==typeof MozWebSocket?sb=MozWebSocket:"undefined"!==typeof WebSocket&&(sb=WebSocket);
function tb(a,b,c,d,e){this.w=d;this.Va=b;this.bc=e;this.fc=c;this.Da=l;this.state=0;this.frames=l;this.Mb=0;a=(a.cb?"wss://":"ws://")+a.host+"/"+a.wa+".ws";U("Connecting to "+a);this.v=new sb(a);var g=this;this.v.onopen=function(){U("Websocket connected.  Sending hello.");g.v.send("version=1")};this.v.onclose=function(){U("Websocket connection was disconnected.");g.v=l;g.close(j)};this.v.onmessage=function(a){g.v!==l&&(a=a.data,0===g.state?"ok"===a?(U("Got hello packet.  WebSocket good."),g.state=
1,g.fc()):"kill"===a&&(U("Shutdown message received from server, likely due to unmatching version numbers."),g.bc()):1===g.state?(g.Mb=Number(a),g.state=2,g.frames=[]):2===g.state&&(g.frames.push(a),g.frames.length==g.Mb&&(a="undefined"!==typeof JSON&&y(JSON.parse)?JSON.parse(g.frames.join("")):ga(g.frames.join("")),g.state=1,ub(g),g.Va(a))))};this.v.onerror=function(){U("WebSocket error.  Closing connection.");g.close()}}
tb.prototype.send=function(a){ub(this);a=ma(a);a=nb(a,16384);this.v.send(""+a.length);for(var b=0;b<a.length;b++)this.v.send(a[b])};tb.prototype.close=function(a){if(!this.Sa&&(this.Sa=j,a||U("Closing WebSocket."),this.Da&&(clearTimeout(this.Da),this.Da=l),this.v&&(this.v.close(),this.v=l),this.w))this.w(),this.w=l};function ub(a){clearTimeout(a.Da);a.Da=setInterval(function(){a.v.send("0");ub(a)},45E3)};function vb(a,b,c,d,e){this.Z=a;this.Ha=b;this.L=c;this.H=d;this.xa=e;this.u=0;this.Ea=l;this.A=0;this.Na=l;if(sb!==l){U("CHOOSER: Starting WebSocket connection.");O(sb!==l,"WebSocket isn't supported.");O(0===this.A,"webSocketState should be START.");O(2!==this.u,"longPollState should not be CONNECTED");this.A=1;try{this.Na=new tb(this.Z,this.Ha,A(this.gc,this),A(this.hc,this),this.xa)}catch(g){wb("WebSocket constructor threw exception: "+g.toString()),xb(this)}}else xb(this);if(3!==this.A){U("CHOOSER: Trying long-poll connection in 450ms.");
var i=this;setTimeout(function(){yb(i)},450)}else yb(this)}w=vb.prototype;w.gc=function(){U("CHOOSER: WebSocket connection connected.");1===this.A||wb("webSocketState should be CONNECTING.");2===this.u?xb(this):(this.A=2,zb(this),this.L&&(this.L(this.Na),this.L=l))};w.hc=function(){U("CHOOSER: WebSocket connection disconnected.");O(0!==this.A,"webSocketState should not be START.");O(3===this.u||2!==this.A,"Was CONNECTED via websocket, but long-polling wasn't canceled.");xb(this)};
function yb(a){0===a.u&&(U("CHOOSER: Starting Long-polling connection."),O(j,"Long-polling isn't supported."),O(2!==a.A,"webSocketState should not be CONNECTED."),a.u=1,a.Ea=new gb(a.Z,a.Ha,A(a.cc,a),A(a.dc,a),a.xa))}w.cc=function(){U("CHOOSER: Long-polling connection connected.");1===this.u||wb("longPollState should be CONNECTING.");2===this.A?zb(this):(this.u=2,xb(this),this.L&&(this.L(this.Ea),this.L=l))};
w.dc=function(){U("CHOOSER: Long-polling connection disconnected.");O(0!==this.u,"longPollState should not be START.");O(3===this.A||2!==this.u,"Was CONNECTED via long-polling, but websocket wasn't canceled.");zb(this)};function zb(a){3!==a.u&&(U("CHOOSER: Canceling long-polling connection."),a.u=3,a.Ea&&(a.Ea.close(),a.Ea=l),Ab(a))}function xb(a){3!==a.A&&(U("CHOOSER: Canceling websocket connection."),a.A=3,a.Na&&(a.Na.close(),a.Na=l),0===a.u&&yb(a),Ab(a))}
function Ab(a){3===a.A&&3===a.u&&a.H&&(U("CHOOSER: Both websocket and long-polling were canceled.  Connection lost."),a.H(),a.H=l)}w.close=function(){zb(this);xb(this);this.H&&(this.H(),this.H=l)};function Bb(){};function Cb(){this.h=[];this.kb=[];this.Ob=[];this.Xa=[];this.Xa[0]=128;for(var a=1;64>a;++a)this.Xa[a]=0;this.reset()}fa(Cb,Bb);Cb.prototype.reset=function(){this.h[0]=1732584193;this.h[1]=4023233417;this.h[2]=2562383102;this.h[3]=271733878;this.h[4]=3285377520;this.vb=this.Ca=0};
function Db(a,b){var c;c||(c=0);for(var d=a.Ob,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var g=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(g<<1|g>>>31)&4294967295}c=a.h[0];for(var i=a.h[1],k=a.h[2],o=a.h[3],m=a.h[4],r,e=0;80>e;e++)40>e?20>e?(g=o^i&(k^o),r=1518500249):(g=i^k^o,r=1859775393):60>e?(g=i&k|o&(i|k),r=2400959708):(g=i^k^o,r=3395469782),g=(c<<5|c>>>27)+g+m+r+d[e]&4294967295,m=o,o=k,k=(i<<30|i>>>2)&4294967295,i=c,c=g;a.h[0]=a.h[0]+c&4294967295;a.h[1]=a.h[1]+i&
4294967295;a.h[2]=a.h[2]+k&4294967295;a.h[3]=a.h[3]+o&4294967295;a.h[4]=a.h[4]+m&4294967295}Cb.prototype.update=function(a,b){y(b)||(b=a.length);var c=this.kb,d=this.Ca,e=0;if(z(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(Db(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(Db(this,c),d=0);this.Ca=d;this.vb+=b};var Eb,Fb,Gb,Hb;function Ib(){return x.navigator?x.navigator.userAgent:l}Hb=Gb=Fb=Eb=n;var Jb;if(Jb=Ib()){var Kb=x.navigator;Eb=0==Jb.indexOf("Opera");Fb=!Eb&&-1!=Jb.indexOf("MSIE");Gb=!Eb&&-1!=Jb.indexOf("WebKit");Hb=!Eb&&!Gb&&"Gecko"==Kb.product}var Lb=Fb,Mb=Hb,Nb=Gb;var Ob;if(Eb&&x.opera){var Pb=x.opera.version;"function"==typeof Pb&&Pb()}else Mb?Ob=/rv\:([^\);]+)(\)|;)/:Lb?Ob=/MSIE\s+([^\);]+)(\)|;)/:Nb&&(Ob=/WebKit\/(\S+)/),Ob&&Ob.exec(Ib());var Qb=l,Rb=l;
function mb(a,b){ba(a)||f(Error("encodeByteArray takes an array as a parameter"));if(!Qb){Qb={};Rb={};for(var c=0;65>c;c++)Qb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Rb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Rb:Qb,d=[],e=0;e<a.length;e+=3){var g=a[e],i=e+1<a.length,k=i?a[e+1]:0,o=e+2<a.length,m=o?a[e+2]:0,r=g>>2,g=(g&3)<<4|k>>4,k=(k&15)<<2|m>>6,m=m&63;o||(m=64,i||(k=64));d.push(c[r],c[g],c[k],c[m])}return d.join("")}
;var qb=function(){var a=1;return function(){return a++}}();function O(a,b){a||f(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Ha(a){var b=Oa(a),a=new Cb;a.update(b);var b=[],c=8*a.vb;56>a.Ca?a.update(a.Xa,56-a.Ca):a.update(a.Xa,64-(a.Ca-56));for(var d=63;56<=d;d--)a.kb[d]=c&255,c/=256;Db(a,a.kb);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.h[d]>>e&255;return mb(b)}
function Sb(){for(var a="",b=0;b<arguments.length;b++)a=ba(arguments[b])?a+Sb.apply(l,arguments[b]):"object"===typeof arguments[b]?a+ma(arguments[b]):a+arguments[b],a+=" ";return a}var Tb=l;function U(){if(Tb){var a=Sb.apply(l,arguments);Tb(a)}}function wb(){if("undefined"!==typeof console){var a=Sb.apply(l,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}var Ma=/^[\-+]?[0-9]*\.?[0-9]+$/;
function ib(a){if("complete"===document.readyState)a();else{var b=n,c=function(){document.body?b||(b=j,a()):setTimeout(c,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",c,n),window.addEventListener("load",c,n)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&c()},n),window.attachEvent("onload",c,n))}}function Na(a,b){return a!==b?a===l?-1:b===l?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}
var Ub=0;function V(a,b,c,d,e){this.Ha=b;this.L=c;this.H=d;this.xa=e;this.$={};this.mc=0;this.Za=[];this.ma=0;b=A(this.ec,this);c=A(this.Zb,this);d=A(this.$b,this);e=A(this.ac,this);this.ra=new vb(a,b,c,d,e)}V.prototype.za=function(a,b,c){var d=++this.mc;Vb(this,{rn:d,payload:a});var e=this,a=setTimeout(function(){var a=e.$[d];a&&(delete e.$[d],a.O&&a.O.Wa&&a.O.Wa())},45E3);this.$[d]={O:{Va:b,Wa:c},Kb:a}};V.prototype.sendRequest=V.prototype.za;w=V.prototype;
w.ec=function(a){if("rn"in a){var b=a.rn,c=this.$[b];c&&(delete this.$[b],clearTimeout(c.Kb),c.O&&c.O.Va&&c.O.Va(a.data))}else"error"in a&&f("A server-side error has occurred: "+a.error),this.Ha&&this.Ha(a)};w.Zb=function(a){U("Realtime connection established.");this.ra=a;this.ma=1;for(a=0;a<this.Za.length;a++)Vb(this,this.Za[a]);this.Za=l;this.L&&(this.L(),this.L=l)};w.$b=function(){this.ra=l;0===this.ma?U("Realtime connection failed."):1===this.ma&&U("Realtime connection lost.");this.close()};
w.ac=function(){U("Connection shutdown command received. Shutting down...");this.xa&&(this.xa(),this.xa=l);this.H=l;this.close()};function Vb(a,b){2===a.ma&&f("Connection has already been closed.");0===a.ma?a.Za.push(b):a.ra.send(b)}w.close=function(){if(2!==this.ma){U("Closing realtime connection.");this.ma=2;this.ra&&(this.ra.close(),this.ra=l);this.H&&(this.H(),this.H=l);for(var a in this.$){var b=this.$[a];delete this.$[a];b!==l&&(b.O&&b.O.Wa&&b.O.Wa(),clearTimeout(b.Kb))}}};
V.prototype.close=V.prototype.close;function Wb(a,b){this.id=Xb++;this.wb={};this.nb={};this.C=[];this.Ia=0;this.rb={};this.da=n;this.$a=1E3;Yb(this,a,b)}var Xb=0;function Zb(a,b){a.o("Listen on "+b);a.nb[b]=j;a.da&&a.Ma.za({action:"listen",path:b},l,function(){a.o("timed out on listen...")})}w=Wb.prototype;w.pa=function(a,b){this.o("Auth with "+a);this.wb[a]=j;var c=this;this.da&&this.Ma.za({action:"auth",secret:a},function(a){b&&b("success"==a.status)},function(){c.o("timed out on auth...")})};
w.rc=function(a){this.o("Unlisten on "+a);delete this.nb[a];var b=this;this.da&&this.Ma.za({action:"unlisten",path:a},l,function(){b.o("timed out on unlisten...")})};w.w=function(a,b){this.rb[a]=b;this.o("onDisconnect",d);var c=this;if(this.da){var d={action:"onDisconnect",path:a.toString(),data:b};this.Ma.za(d,function(a){"success"!==a.status&&f("onDisconnect failed: "+ma(a.data))},function(){c.o("timed out on onDisconnect...")})}};
w.put=function(a,b,c,d){a={action:"put",path:a.toString(),data:b};y(d)&&(a.hash=d);this.o("put",a);this.C.push({Hb:a,B:c});this.Ia++;c=this.C.length-1;this.da&&$b(this,c)};function $b(a,b){var c=a.C[b].B;a.Ma.za(a.C[b].Hb,function(d){a.o("put response",d);delete a.C[b];a.Ia--;0===a.Ia&&(a.C=[]);c&&c(d.status)},function(){a.o("timed out on put...")})}
function Yb(a,b,c){var d=(new Date).getTime(),e=l;a.Ma=new V(b,function(b){a.o("handleServerMessage",b);"data"in b?c(b.data.path,b.data.data):"timestamp"in b?Ub=b.timestamp-(new Date).getTime():f("Unrecognized message returned from server: "+ma(b))},function(){a.da=j;e=(new Date).getTime();for(var b in a.wb)a.pa(b);for(var c in a.nb)Zb(a,c);for(c in a.rb)a.w(c,a.rb[c]);for(b=0;b<a.C.length;b++)a.C[b]&&$b(a,b)},function(){a.da=n;ac(a);e&&(3E4<(new Date).getTime()-e&&(a.$a=1E3),e=l);var g=Math.max(0,
a.$a-((new Date).getTime()-d)),g=Math.random()*g;setTimeout(function(){Yb(a,b,c)},g);a.$a=Math.min(3E4,1.3*a.$a)},function(){f(Error("Firebase connection was forcefully killed by the server.  Will not attempt reconnect."))})}function ac(a){for(var b=0;b<a.C.length;b++){var c=a.C[b];c&&c.Hb.hash&&(c.B&&c.B("disconnect"),delete a.C[b],a.Ia--)}0===a.Ia&&(a.C=[])}w.o=function(){U(this.id+":",arguments)};function bc(a){this.i=J;this.m=a}function cc(a,b){var c=new W(a.m,b);return new P(a.i.e(b),c)}function X(a,b,c){a.i=a.i.Aa(b,c)}function ec(a,b,c,d){for(var e=a.i.e(b),c=c.i.e(b),d=R(d,b),g=n,i=d;i!==l;){if(i.c()!==l){g=j;break}i=i.parent()}if(g)return n;d=fc(c,e,d);return d!==e?(a.i=a.i.Aa(b,d),j):n}bc.prototype.z=function(){return cc(this,new E("/")).z()};
function fc(a,b,c){if(c.a())return a;if(c.c()!==l)return b;a=a||J;c.p(function(d){var d=d.name(),e=a.t(d),g=b.t(d),i=R(c,d),e=fc(e,g,i);a=a.q(d,e)});return a};function gc(a,b,c){this.j=a;this.ba=[];this.ta=c;"default"===this.j.N()?this.d=b:(this.d=J,hc(this,b,ic(this,b,c)))}gc.prototype.addEventListener=function(a,b,c){this.ba.push({type:a,Ba:b});for(var d=ic(this,this.d,this.ta),e=0;e<d.length;e++)d[e].type===a&&c.push({Ba:b,T:d[e].T,La:d[e].La})};gc.prototype.removeEventListener=function(a,b){for(var c=n,d=0;d<this.ba.length;d++){var e=this.ba[d];if(e.type===a&&e.Ba===b){this.ba.splice(d,1);c=j;break}}return{pc:c,Eb:0===this.ba.length}};
function hc(a,b,c){var d=[],e=a.j;y(a.j.la)&&d.push(function(a){return 0<=(a!==e.la?a<e.la?-1:1:0)});y(a.j.ea)&&d.push(function(a){return 0>=(a!==e.ea?a<e.ea?-1:1:0)});y(a.j.aa)&&d.push(function(a,b){return 0<=Na(b,e.aa)});y(a.j.fa)&&d.push(function(a,b){return 0>=Na(b,e.fa)});var g=l,i=l;if(y(a.j.Y))if(y(a.j.aa)){if(g=jc(b,d,a.j.Y,n)){var k=b.t(g).f();d.push(function(a,b){return b<k||b===k&&a<=g})}}else if(i=jc(b,d,a.j.Y,j)){var o=b.t(i).f();d.push(function(a,b){return b>o||b===o&&a>=i})}for(var m=
[],r=[],u=[],B=[],s=0;s<c.length;s++){var F=c[s].type,p=c[s].T,t=p.name(),G=p.b;switch(F){case "child_added":kc(d,t,G)&&(a.d=a.d.q(t,G),r.push(p));break;case "child_removed":a.d.t(t).a()||(a.d=a.d.q(t,l),m.push(c[s]));break;case "child_changed":!a.d.t(t).a()&&kc(d,t,G)&&(a.d=a.d.q(t,G),B.push(p));break;case "child_moved":var F=!a.d.t(t).a(),ra=kc(d,t,G);F?ra?(a.d=a.d.q(t,G),u.push(p)):(p=a.j.path.k(t),m.push(new C("child_removed",new P(a.d.t(t),p))),a.d=a.d.q(t,l)):ra&&(a.d=a.d.q(t,G),r.push(p))}}var dc=
g||i;if(dc){var Fc=(s=i!==l)?a.d.Ab():a.d.Cb(),ob=n,pb=n;(s?b.mb:b.p).call(b,function(b,c){if(ob){var d=a.j.path.k(b);m.push(new C("child_removed",new P(a.d.t(b),d)));a.d=a.d.q(b,l)}else pb&&(d=a.j.path.k(b),r.push(new P(c,d)),a.d=a.d.q(b,c));b===Fc&&(pb=j);b===dc&&(ob=j);if(pb&&ob)return j})}for(s=0;s<r.length;s++)p=r[s],b=a.d.G(p.name(),p.b),m.push(new C("child_added",p,b));for(s=0;s<u.length;s++)p=u[s],b=a.d.G(p.name(),p.b),m.push(new C("child_moved",p,b));for(s=0;s<B.length;s++)p=B[s],b=a.d.G(p.name(),
p.b),m.push(new C("child_changed",p,b));u=n;!a.ta&&0<c.length&&"value"===c[c.length-1].type&&(u=a.ta=j);a.ta&&(0<m.length||u)&&m.push(new C("value",new P(a.d,a.j.path)));return m}function jc(a,b,c,d){var e=l;(d?a.mb:a.p).call(a,function(a,d){if(kc(b,a,d)&&(e=a,c--,0===c))return j});return e}function kc(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.f()))return n;return j}
function ic(a,b,c){var d=[];if(!b.Q()){var e=l;b.p(function(b,c){var k=a.j.path.k(b);d.push(new C("child_added",new P(c,k),e));e=b})}c&&d.push(new C("value",new P(b,a.j.path)));return d};function lc(a){this.Z=a;this.ja=new bc(this);this.r=new bc(this);this.K=new bc(this);this.S=new Q;this.gb=new Q;this.U=new Q;this.F=new Q;this.pb=J;var b=this;this.V=new Wb(this.Z,function(a,d){mc(b,a,d)})}lc.prototype.pa=function(a,b){this.V.pa(a,b)};
function nc(a,b,c,d){var e=b.path.s,g=R(a.U,e),i=g.c();if(i===l){var i={M:{}},k=n;bb(g,function(a){a.c()&&a.c().na&&(k=j)});k||(i.na=oc(a,e.toString()),ab(g,function(a){a=a.c();a!==l&&a.na&&(a.na(),a.na=l)}));S(g,i)}var g=b.N(),o=i.M[g];o||(o=a.K.i.e(e),a=T(a.F,e),o=new gc(b,o,a),i.M[g]=o);b=[];o.addEventListener(c,d,b);pc(b)}
function qc(a,b,c,d){var e=b.path.s,g=R(a.U,e),i=g.c(),k;if(i!==l){if("default"!==b.N()){if(k=i.M[b.N()])k=k.removeEventListener(c,d),k.Eb&&delete i.M[b.N()]}else{var b=l,o=n,m;for(m in i.M)if(k=i.M[m].removeEventListener(c,d),k.pc){b=m;o=k.Eb;break}o&&delete i.M[b]}if(Ya(i.M)){if(i.na){var r=T(a.F,e);cb(g,function(b){b.na=oc(a,b.path().toString());r&&S(R(a.F,b.path()),j)});i.na()}S(g,l)}}}function oc(a,b){Zb(a.V,b);return A(a.V.rc,a.V,b)}
function mc(a,b,c){if(9<=b.length&&b.lastIndexOf(".priority")===b.length-9)b=new E(b.substring(0,b.length-9)),c!==l&&Ma.test(c)&&(c=Number(c)),X(a.ja,b,a.ja.i.e(b).ib(c));else{b=new E(b);X(a.ja,b,La(c));var d=n;bb(R(a.U,b),function(a){a.c()&&a.c().Db&&(d=j)},j);if(!d&&(c=R(a.U,b).c()))c.Db=j}ec(a.r,b,a.ja,a.S)?rc(a,sc(a,b)):tc(a,b)}function uc(a,b){bb(R(a.U,b),function(a){if(a.c()&&a.c().Db)return j});return n}
function tc(a,b){var c=[],d=a.pb,e=a.K.i;a.pb=a.K.i;var g=d.e(b),i=e.e(b),k=vc(a,b,g,i,c),g=g.f()!==i.f();if(k||g)for(var o=g,m=R(a.U,b);m.parent()!==l;){var r=d.e(m.path()),u=e.e(m.path()),g=m.parent();if(g.c()){var B=g.path(),i=e.e(B),s=[],m=Ea(m.path()),B=new W(a,B.k(m));if(r.a())r=i.G(m,u),s.push(new C("child_added",new P(u,B),r));else if(u.a())s.push(new C("child_removed",new P(r,B)));else if(k&&(r=i.G(m,u),s.push(new C("child_changed",new P(u,B),r))),o)r=i.G(m,u),s.push(new C("child_moved",
new P(u,B),r)),k=j;T(a.F,g.path())&&(Ea(g.path())||a.name(),o=new W(a,g.path()),s.push(new C("value",new P(i,o))));c.push({path:g.path().toString(),Qa:s})}m=g;o=n}for(d=0;d<c.length;d++)if(s=a,e=c[d].Qa,o=new E(c[d].path),k=R(s.U,o).c(),k!==l){g=k.M;i=[];s=s.pb.e(o);o=h;for(o in g){u=k.M[o];B=s;r=e;m=i;"default"!==u.j.N()?r=hc(u,B,r):(u.d=B,u.ta=u.ta||0<r.length&&"value"===r[r.length-1].type);for(B=0;B<r.length;B++){var F=r[B],p=F.type;"value"===F.type&&!F.T.Ra()?p+="("+F.T.z()+")":"value"!==F.type&&
(p+=" "+F.T.name());U(u.j.path.m.V.id+":event:"+u.j.path.s+":"+u.j.N()+":"+p);for(p=0;p<u.ba.length;p++){var t=u.ba[p];r[B].type===t.type&&m.push({Ba:t.Ba,T:F.T,La:F.La})}}}pc(i)}}
function vc(a,b,c,d,e){var g;c===d&&(g=n);c.Q()&&d.Q()?g=c.c()!==d.c():c.Q()?(wc(a,b,J,d,e),g=j):d.Q()?(wc(a,b,c,J,e),g=j):g=wc(a,b,c,d,e);c=n;T(a.F,b)||(ab(R(a.U,b),function(b){if(!T(a.F,b.path())){var c=new W(a,b.path());e.push({path:b.path(),Qa:[new C("value",new P(J,c))]})}}),c=j,R(a.F,b).clear(),S(R(a.F,b),j));if(g||c)c=new W(a,b),e.push({path:b.toString(),Qa:[new C("value",new P(d,c))]});return g}
function wc(a,b,c,d,e){var g=n,i=[],k=!R(a.U,b).a(),o=[],m=[],r=[],u={},B={},s,F,p,t,G,ra;s=c.sa();p=sa(s);F=d.sa();for(t=sa(F);p!==l||t!==l;){c=p===l?1:t===l?-1:p.key===t.key?0:Ka({name:p.key,ga:p.value.f()},{name:t.key,ga:t.value.f()});if(0>c)g=u[p.key],y(g)?(r.push({zb:p,Lb:o[g]}),o[g]=l):(B[p.key]=m.length,m.push(p)),g=j,p=sa(s);else{if(0<c)g=B[t.key],y(g)?(r.push({zb:m[g],Lb:t}),m[g]=l):(u[t.key]=o.length,o.push(t)),g=j;else{c=b.k(t.key);if(ra=vc(a,c,p.value,t.value,e))G=d.G(t.key,t.value),p=
new W(a,c),i.push(new C("child_changed",new P(t.value,p),G)),g=j;p=sa(s)}t=sa(F)}if(!k&&g)return j}for(k=0;k<m.length;k++)if(u=m[k])c=b.k(u.key),p=new W(a,c),vc(a,c,u.value,J,e),i.push(new C("child_removed",new P(u.value,p)));for(k=0;k<o.length;k++)if(m=o[k])c=b.k(m.key),p=new W(a,c),G=d.G(m.key,m.value),vc(a,c,J,m.value,e),i.push(new C("child_added",new P(m.value,p),G));for(k=0;k<r.length;k++)m=r[k].zb,o=r[k].Lb,c=b.k(o.key),p=new W(a,c),G=d.G(o.key,o.value),i.push(new C("child_moved",new P(o.value,
p),G)),(ra=vc(a,c,m.value,o.value,e))&&i.push(new C("child_changed",new P(o.value,p),G));0<i.length&&e.push({path:b.toString(),Qa:i});return g}function pc(a){for(var b=0;b<a.length;b++){var c=a[b].Ba;c(a[b].T,a[b].La)}}
lc.prototype.fb=function(a,b,c,d){c!==l&&Ma.test(c)&&(c=Number(c));this.o("set",{path:a.toString(),value:b});var e=qb(),g=this;S(R(this.S,a),e);X(this.r,a,La(b,c));b=this.r.i.e(a).z(j);xc(this,a,b,function(b){O("success"===b,"put failed.  WHAT TO DO!? WHAT TO DO!?");var b=R(g.S,a),c=b.c();O(c!==l,"setWithPriority: pendingSet should not be null.");c===e&&(S(b,l),uc(g,a)&&(ec(g.r,a,g.ja,g.S),b=sc(g,a),rc(g,b)));d&&d(j)});b=sc(this,a);yc(this,a);rc(this,b)};
function yc(a,b){var c=R(a.gb,b);bb(c,function(b){zc(a,b)});zc(a,c);ab(c,function(b){zc(a,b)})}function zc(a,b){var c=b.c();if(c!==l){for(var d=-1,e=0;e<c.length;e++)if(c[e].status===Ac)O(d===e-1,"All SENT items should be at beginning of queue."),d=e,c[e].status=Bc;else if(c[e].hb(),c[e].B){var g=T(a.F,b.path())?cc(a.K,b.path()):l;c[e].B(n,g)}-1===d?S(b,l):c.length=d+1}}var Ac=2,Bc=4;
function Cc(a,b,c,d){function e(){}a.o("transaction on "+b);var g=new W(a,b);g.qb("value",e);var c={Gb:b,update:c,B:d,Fb:qb(),Jb:0,hb:function(){g.ob("value",e)}},d=a.K,i=c.update(d.i.e(b).z());if(y(i)){Ta("transaction failed: Data returned ",i);var k=a.r.i.e(b).f();X(d,b,La(i,k));tc(a,b);c.status=1;b=R(a.gb,b);d=b.c()||[];d.push(c);S(b,d);Dc(a)}else c.hb(),c.B&&(a=T(a.F,b)?cc(a.K,b):l,c.B(n,a))}function Dc(a,b){var c=b||a.gb;b||Ec(a,c);c.a()||(c.c()!==l?Gc(a,c):c.p(function(b){Dc(a,b)}))}
function Gc(a,b){var c=Hc(a,b);if(0!==c.length){var d=b.path();if(c[0].status!==Ac&&c[0].status!==Bc){for(var e=0;e<c.length;e++)O(1===c[e].status,"tryToSendTransactionForNode_: items in queue should all be run."),c[e].status=Ac,c[e].Jb++;var g=a.r.i.e(d).hash();X(a.r,d,a.K.i.e(d));var i=a.r.i.e(d).z(j),k=qb();S(R(a.S,d),k);xc(a,d,i,function(g){a.o("transaction put response",{path:d.toString(),status:g});var i=R(a.S,d),r=i.c();O(r!==l,"tryToSendTransactionsForNode_: pendingSet should not be null.");
r===k&&(S(i,l),X(a.r,d,a.ja.i.e(d)));if("success"===g){for(e=0;e<c.length;e++)c[e].status=3,c[e].B&&(g=T(a.F,d),O(g,"Transaction completed successfully but we don't have data for this location!?"),g=cc(a.K,b.path()),c[e].B(j,g)),c[e].hb();Dc(a)}else if("datastale"===g||"disconnect"===g){if("datastale"===g)for(e=0;e<c.length;e++)c[e].status=c[e].status===Bc?5:1;else if("disconnect"===g)for(e=0;e<c.length;e++)c[e].status=6;g=sc(a,d);rc(a,g)}else O(n,"Got unexpected put response to transaction: "+g)},
g)}}}
function rc(a,b){var c=b.path();X(a.K,c,a.r.i.e(c));var d=Hc(a,b);if(0!==d.length){for(var e=a.K.i.e(c),g=0;g<d.length;g++){var i=Fa(c,d[g].Gb),k=n,o;O(i!==l,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[g].status)k=j,o="set";else if(6===d[g].status)k=j,o="disconnect";else if(1===d[g].status)if(25<=d[g].Jb)k=j,o="maxretry";else{var m=d[g].update(e.e(i).z());y(m)?(Ta("transaction failed: Data returned ",m),e=e.Aa(i,La(m))):(k=j,o="nodata")}k&&(d[g].hb(),d[g].status=3,d[g].B&&
(k=new W(a,d[g].Gb),i=new P(e.e(i),k),d[g].B(n,i,o)))}d=a.r.i.e(c).f();X(a.K,c,e.ib(d));Dc(a)}tc(a,c)}function sc(a,b){for(var c,d=a.gb;(c=H(b))!==l&&d.c()===l;)d=R(d,c),b=I(b);return d}function Hc(a,b){var c=[];Ic(a,b,c);c.sort(function(a,b){return a.Fb-b.Fb});return c}function Ic(a,b,c){var d=b.c();if(d!==l)for(var e=0;e<d.length;e++)c.push(d[e]);b.p(function(b){Ic(a,b,c)})}
function Ec(a,b){var c=b.c();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;S(b,0<c.length?c:l)}b.p(function(b){Ec(a,b)})}w=lc.prototype;w.ub=function(a,b,c){var d=qb(),e=this;xc(this,a.toString()+"/.priority",b,function(b){var i=R(e.S,a),k=i.c();O(k!==l,"setPriority: pendingSet should not be null.");k===d&&(S(i,l),ec(e.r,a,e.ja,e.S),i=sc(e,a),rc(e,i));c&&c("success"===b)});S(R(this.S,a),d);X(this.r,a,cc(this.r,a).b.ib(b));rc(this,sc(this,a))};
w.eb=function(a,b){this.V.w(a,b)};function xc(a,b,c,d,e){a.V.put(b,c,d,e)}w.toString=function(){return(this.Z.cb?"https://":"http://")+this.Z.host+"/"+Da(this.Z.wa)};w.name=function(){return this.Z.wa};w.o=function(){U(this.V.id+":",arguments)};function Jc(){this.tb={}}Jc.Bb=function(){return Jc.Tb||(Jc.Tb=new Jc)};function Y(a,b,c,d,e,g){this.path=a;this.Y=b;this.aa=Ma.test(c)?Number(c):c;this.la=d;this.fa=Ma.test(e)?Number(e):e;this.ea=g;y(this.aa)&&y(this.fa)&&y(this.Y)&&f("firebase.Query: Can't combine startAt(), endAt(), and limit().")}Y.prototype.qb=function(a,b){L("firebase.Query.on",2,2,arguments.length);Va("firebase.Query.on",a);N("firebase.Query.on",2,b,n);nc(this.path.m,this,a,b);return b};Y.prototype.on=Y.prototype.qb;
Y.prototype.ob=function(a,b){L("firebase.Query.off",2,2,arguments.length);Va("firebase.Query.off",a);N("firebase.Query.off",2,b,n);qc(this.path.m,this,a,b)};Y.prototype.off=Y.prototype.ob;Y.prototype.ic=function(a,b){function c(g){e&&(e=n,d.ob(a,c),b(g))}L("firebase.Query.once",2,2,arguments.length);Va("firebase.Query.once",a);N("firebase.Query.once",2,b,n);var d=this,e=j;this.qb(a,c)};Y.prototype.once=Y.prototype.ic;
Y.prototype.Ub=function(a){L("firebase.Query.limit",1,1,arguments.length);(!ca(a)||Math.floor(a)!==a||0>=a)&&f("firebase.Query.limit: First argument must be a positive integer.");return new Y(this.path,a,this.aa,this.la,this.fa,this.ea)};Y.prototype.limit=Y.prototype.Ub;Y.prototype.oc=function(a,b){L("firebase.Query.startAt",0,2,arguments.length);Ua("firebase.Query.startAt",1,a,j);Wa("firebase.Query.startAt",b);y(a)||(b=a=l);return new Y(this.path,this.Y,a,b,this.fa,this.ea)};
Y.prototype.startAt=Y.prototype.oc;Y.prototype.Pb=function(a,b){L("firebase.Query.endAt",0,2,arguments.length);Ua("firebase.Query.endAt",1,a,j);Wa("firebase.Query.endAt",b);return new Y(this.path,this.Y,this.aa,this.la,a,b)};Y.prototype.endAt=Y.prototype.Pb;Y.prototype.N=function(){var a=[];y(this.aa)&&a.push({sp:this.aa});y(this.la)&&a.push({sn:this.la});y(this.fa)&&a.push({ep:this.fa});y(this.ea)&&a.push({en:this.ea});y(this.Y)&&a.push({l:this.Y});return 0===a.length?"default":ma(a)};var Kc=function(){var a=0,b=[];return function(){var c=(new Date).getTime()+Ub,d=c===a;a=c;for(var e=Array(8),g=7;0<=g;g--)e[g]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(c%64),c=Math.floor(c/64);O(0===c);c=e.join("");if(d){for(g=11;0<=g&&63===b[g];g--)b[g]=0;b[g]++}else for(g=0;12>g;g++)b[g]=Math.floor(64*Math.random());for(g=0;12>g;g++)c+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(b[g]);O(20===c.length,"NextPushId: Length should be 20.");
return c}}();function W(){var a,b;Y.call(this,this);if(arguments[0]instanceof lc)this.m=arguments[0],this.s=arguments[1];else{L("new Firebase",1,1,arguments.length);a=arguments[0];var c="",d="",e=n;b="";if(z(a)){var g=a.indexOf("://");0<g&&(e="https"===a.substring(0,g),a=a.substring(g+3));g=a.indexOf("/");0<g&&(c=a.substring(0,g),a=a.substring(g+1),g=a.indexOf("/"),0<g?(d=a.substring(0,g),b=a.substring(g)):(d=a,b="/"))}a={host:c,cb:e,wa:d};b=new E(b);c=b.toString();(!z(a.host)||0===a.host.length||!Ra(a.wa)||0!==
c.length&&(!z(c)||0===c.length||Qa.test(c)))&&f(Error(M("new Firebase",1,n)+"must be a valid firebase URL."));c=Jc.Bb();d=(a.cb?"https://":"http://")+a.host+"/"+a.wa;e=c.tb[d];e||(e=new lc(a),c.tb[d]=e);this.m=e;this.s=b}}fa(W,Y);var Lc=W,Mc=["Firebase"],Z=x;!(Mc[0]in Z)&&Z.execScript&&Z.execScript("var "+Mc[0]);for(var Nc;Mc.length&&(Nc=Mc.shift());)!Mc.length&&y(Lc)?Z[Nc]=Lc:Z=Z[Nc]?Z[Nc]:Z[Nc]={};
W.prototype.name=function(){L("Firebase.name",0,0,arguments.length);return this.s.a()?this.m.name():Ea(this.s)};W.prototype.name=W.prototype.name;W.prototype.k=function(a){L("Firebase.child",1,1,arguments.length);ca(a)?a=""+a:a instanceof E||Xa("Firebase.child",a);return new W(this.m,this.s.k(a))};W.prototype.child=W.prototype.k;W.prototype.parent=function(){L("Firebase.parent",0,0,arguments.length);var a=this.s.parent();return a===l?l:new W(this.m,a)};W.prototype.parent=W.prototype.parent;
W.prototype.toString=function(){L("Firebase.toString",0,0,arguments.length);return this.parent()===l?this.m.toString():this.parent().toString()+"/"+Da(this.name())};W.prototype.toString=W.prototype.toString;W.prototype.set=function(a,b){L("Firebase.set",1,2,arguments.length);Sa("Firebase.set",a,n);N("Firebase.set",2,b,j);(".length"===this.name()||".keys"===this.name())&&f("Firebase.set failed: "+this.name()+" is a read-only object.");return this.m.fb(this.s,a,l,b)};W.prototype.set=W.prototype.set;
W.prototype.fb=function(a,b,c){L("Firebase.setWithPriority",2,3,arguments.length);Sa("Firebase.setWithPriority",a,n);Ua("Firebase.setWithPriority",2,b,n);N("Firebase.setWithPriority",3,c,j);(".length"===this.name()||".keys"===this.name())&&f("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.m.fb(this.s,a,b,c)};W.prototype.setWithPriority=W.prototype.fb;
W.prototype.remove=function(a){L("Firebase.remove",0,1,arguments.length);N("Firebase.remove",1,a,j);this.set(l,a)};W.prototype.remove=W.prototype.remove;W.prototype.transaction=function(a,b){L("Firebase.transaction",1,2,arguments.length);N("Firebase.transaction",1,a,n);N("Firebase.transaction",2,b,j);(".length"===this.name()||".keys"===this.name())&&f("Firebase.transaction failed: "+this.name()+" is a read-only object.");Cc(this.m,this.s,a,b)};W.prototype.transaction=W.prototype.transaction;
W.prototype.ub=function(a,b){L("Firebase.setPriority",1,2,arguments.length);Ua("Firebase.setPriority",1,a,n);N("Firebase.setPriority",2,b,j);a!==l&&Ma.test(a)&&(a=Number(a));this.m.ub(this.s,a,b)};W.prototype.setPriority=W.prototype.ub;W.prototype.push=function(a,b){L("Firebase.push",0,2,arguments.length);Sa("Firebase.push",a,j);N("Firebase.push",2,b,j);var c=this.k(Kc());"undefined"!==typeof a&&a!==l&&c.set(a,b);return c};W.prototype.push=W.prototype.push;
W.prototype.kc=function(){L("Firebase.removeOnDisconnect",0,0,arguments.length);this.m.eb(this.s,l)};W.prototype.removeOnDisconnect=W.prototype.kc;W.prototype.eb=function(a){L("Firebase.setOnDisconnect",1,1,arguments.length);Sa("Firebase.setOnDisconnect",a,n);this.m.eb(this.s,a)};W.prototype.setOnDisconnect=W.prototype.eb;W.prototype.pa=function(a,b){L("Firebase.auth",1,2,arguments.length);Sa("Firebase.auth",a,n);this.m.pa(a,b)};W.prototype.auth=W.prototype.pa;
W.enableLogging=function(a){a===j?"undefined"!==typeof console&&(Tb=A(console.log,console)):Tb=a?a:l};var $={};W.TEST_HOOKS=$;$.lc=function(){return Jc.Bb().tb};$.repos=$.lc;$.Sb=function(a){var b=K.prototype.hash;K.prototype.hash=a;return function(){K.prototype.hash=b}};$.hijackHash=$.Sb;$.N=function(a){return a.N()};$.queryIdentifier=$.N;$.Nb=V;$.RealTimeConnection=$.Nb;})();